// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RNMA.Data;

#nullable disable

namespace RNMA.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230607075430_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RNMA.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "this is post 1",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "this is post 2",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "this is post 3",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "this is post 4",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "this is post 5",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "this is post 6",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
